### ISSUE TITLE
Cannot use it with webpack and uglifyJs

### ISSUE THREAD

**Issue by gaspaonrocks** [NigelOToole/direction-reveal#4]
Apparently webpack cannot bundle the dependency to your module because of some transpilation config...

It works if I copy it into my project though... 

The closest issues about this is : 
 - [Error from UglifyJs - Name Expected](https://github.com/webpack/webpack/issues/5682)
 - [ERROR in bundle.js from UglifyJs Name expected](https://stackoverflow.com/questions/45870467/error-in-bundle-js-from-uglifyjs-name-expected)

Any intention of looking into it ? It would be a shame to prevent people using webpack from using your work...

**Comment by NigelOToole** [comment]
I have pushed an update which I think resolves this issue. I have removed the module and js:next definitions form package.json because I mistakenly believed that these did not need to be transpiled. Can you check this works for you? As I am less familiar with Webpack any advice regarding compatibility with it would be appreciated.

**Comment by gaspaonrocks** [comment]
@NigelOToole 

Hey ! Sorry for the late reply. 

If Ihave time I'll look into it today, otherwise I'll do it tomorrow.
